name: release

on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Build Alt
        run: |
          GOOS=darwin GOARCH=amd64 go build -o alt-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o alt-darwin-arm64 .
          GOOS=linux GOARCH=amd64 go build -o alt-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o alt-linux-arm64 .
      -
        name: Package Alt
        run: |
          mkdir darwin-amd64 darwin-arm64 linux-amd64 linux-arm64
          mv alt-darwin-amd64 darwin-amd64/alt
          mv alt-darwin-arm64 darwin-arm64/alt
          mv alt-linux-amd64 linux-amd64/alt
          mv alt-linux-arm64 linux-arm64/alt
          (cd darwin-amd64 && tar cfJ ../darwin-amd64.apkg *)
          (cd darwin-arm64 && tar cfJ ../darwin-arm64.apkg *)
          (cd linux-amd64 && tar cfJ ../linux-amd64.apkg *)
          (cd linux-arm64 && tar cfJ ../linux-arm64.apkg *)
      - name: Release Alt
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            darwin-amd64.apkg
            darwin-arm64.apkg
            linux-amd64.apkg
            linux-arm64.apkg
      
